apiVersion: v1
kind: ReplicationController
metadata:
  name: couchbase-rc
spec:
  replicas: 1
  selector:
    app: couchbase-pod
  template:
    metadata:
      labels:
        app: couchbase-pod
    spec:
      containers:
      - name: couchbase
        image: arungupta/couchbase:k8s
        ports:
        - containerPort: 8091
---
apiVersion: v1
kind: Service
metadata: 
  name: couchbase-service
  labels: 
    app: couchbase-service
spec: 
  ports:
    - port: 8091
  selector: 
    app: couchbase-pod
  type: LoadBalancer
