apiVersion: v1
kind: Pod
# labels attached to this Pod
metadata:
  name: couchbase-pod
spec:
  containers:
  - name: arungupta/couchbase
    # Docker image that will run in this Pod
    image: couchbase
    ports:
    - containerPort: 8091
